apiVersion: v1
kind: Service
metadata:
  name: sixpack-api
  labels:
    name: sixpack-api
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000 
  selector:
    name: sixpack-api
