apiVersion: v1
kind: Service
metadata:
  name: sixpack-web
  labels:
    name: sixpack-web
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    name: sixpack-web
